namespace Project.Core.Definitions.Report
{
    /// <summary>
    /// Identifies the specific type of report generated by the simulation.
    /// Each value maps to a distinct event or milestone that the player receives in their inbox.
    /// </summary>
    public enum ReportType
    {
        MonthlyFinance,
        ProductProgress,
        ProductLaunch,
        SalesUser,
        SupportBug,
        Candidate,
        OfferResponse,
        TeamMorale,
        MarketTrend,
        CompetitorLaunch,
        InfrastructureIncident,
        HardwareDefect,
        MarketingCampaign,
        ResearchCompletion,
        ContractCompletion,
        /// <summary>
        /// Report generated when a game event or crisis fires and effects are applied.
        /// Added in Plan 2M, GDD_15.
        /// </summary>
        CrisisEvent
    }
}
