using UnityEngine;
using UnityEngine.UIElements;

namespace Project.Presentation.UI.Shell
{
    /// <summary>
    /// Fixes the UIDocument panel layout so the root UXML content fills the full viewport.
    /// Unity's UIDocument wraps cloned VisualTreeAsset content in a TemplateContainer
    /// that does not stretch by default. This MonoBehaviour sets flex-grow on both
    /// rootVisualElement and the TemplateContainer so .main-shell can fill the panel.
    /// 
    /// Attach to the same GameObject as the UIDocument (UIShell).
    /// Phase 4B structural fix only — no routing, no gameplay logic.
    /// </summary>
    [RequireComponent(typeof(UIDocument))]
    public sealed class UIShellLayoutFixer : MonoBehaviour
    {
        private void OnEnable()
        {
            var uiDocument = GetComponent<UIDocument>();
            if (uiDocument == null)
            {
                Debug.LogError("[UI] UIShellLayoutFixer — UIDocument component not found.");
                return;
            }

            var root = uiDocument.rootVisualElement;
            if (root == null)
            {
                Debug.LogError("[UI] UIShellLayoutFixer — rootVisualElement is null.");
                return;
            }

            // Ensure rootVisualElement fills the panel.
            root.style.flexGrow = 1;

            // The first child is the TemplateContainer generated by VisualTreeAsset.CloneTree().
            // It must also flex-grow to pass height down to .main-shell.
            if (root.childCount > 0)
            {
                var templateContainer = root[0];
                templateContainer.style.flexGrow = 1;
            }
        }
    }
}
