using Project.Core.Definitions.SaveLoad;

namespace Project.Core.Requests.SaveLoad
{
    /// <summary>
    /// Request DTO carrying the parameters required to initiate a save operation.
    /// Passed to ISaveService.Save() by the calling use case.
    /// OverrideSaveId, when non-null, replaces the GUID generated by SaveService.
    /// Used by SaveSlotManager for quick save (fixed ID "quicksave") and validation saves.
    /// </summary>
    public sealed class SaveRequest
    {
        /// <summary>Human-readable display name for the save slot (e.g. "Save 1", "Before Big Decision").</summary>
        public string SaveName { get; }

        /// <summary>The category of this save operation.</summary>
        public SaveType Type { get; }

        /// <summary>
        /// When non-null, SaveService uses this ID instead of generating a new GUID.
        /// Used for fixed-ID slots such as the quick save ("quicksave") and validation saves.
        /// Null for all standard manual saves and autosaves.
        /// </summary>
        public string OverrideSaveId { get; }

        /// <summary>Creates a SaveRequest with an auto-generated save ID.</summary>
        public SaveRequest(string saveName, SaveType type)
        {
            SaveName       = saveName;
            Type           = type;
            OverrideSaveId = null;
        }

        /// <summary>Creates a SaveRequest with a caller-supplied fixed save ID.</summary>
        public SaveRequest(string saveName, SaveType type, string overrideSaveId)
        {
            SaveName       = saveName;
            Type           = type;
            OverrideSaveId = overrideSaveId;
        }
    }
}
